# k8s/01-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://user:password@host:port/dbname" #
  SECRET_KEY: "your-super-secret-django-key" #