from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

###
# Create a router and register our viewsets with it.
#
# A router automatically generates the URL patterns for a viewset.
router = DefaultRouter()
router.register(r'jobs', views.JobViewSet, basename='job')
# Add other viewsets here if you create more

###
# Define URL patterns for our standalone views
###
# The API URLs are now determined automatically by the router.
# For stand-alone views, we define them manually.
urlpatterns = [
    # Path for user registration
    path('auth/register/', views.RegisterView.as_view(), name='register'),

    # Path for retrieving/updating the current user's profile
    path('users/me/', views.ManageUserView.as_view(), name='manage-user'),

    # Include the URLs generated by the router
    path('', include(router.urls)),
]